graph TD
    A[PC A<br/>192.168.1.10] --> SW[Switch Cisco 2960<br/>192.168.1.254]
    B[PC B<br/>192.168.1.20] --> SW
    C[PC C - Atacante<br/>192.168.1.30] --> SW
    SW --> |Puerto Fa0/1| A
    SW --> |Puerto Fa0/2| B  
    SW --> |Puerto Fa0/3| C